### ISSUE TITLE
ejs-compile show error

### ISSUE THREAD

**Issue by cesarin3134** [jonnsl/ejs-compile#1]
i installed ejs compile module, i launch from terminal 
    ejs-compile vista.ejs  
    and i get this error -> env: node\r: No such file or directory

**Comment by cesarin3134** [comment]
i fixed this problem changing the line-end of the file ejs-compile file to unix.

**Comment by godspeedelbow** [comment]
yeah, that fixes it. thanks @cesarin3134 

`sed 's/^M$//' ejs-compile > ejs-compile.js` creates new file `ejs-compile.js` which does work

**Comment by cesarin3134** [comment]
for nothing @godspeedelbow ;)
